training {
  task = "ere"
  dataset = "ace05"

  data_dir = ${ASP}/data/ace05_ere/
  model_dir = ${ASP}/data/ace05_ere/
  log_root = ${ASP}/data/ace05_ere/

  # Learning
  use_amp = true
  optimizer = "adamw"
  plm_scheduler = "linear_with_warmup" # constant / constant_with_warmup / linear_with_warmup
  task_scheduler = "linear_with_warmup"
  plm_learning_rate = 5e-5
  task_learning_rate = 1e-4

  adam_eps = 1e-8
  adam_weight_decay = 0.1

  init_std = 0.02

  feature_emb_size = 20
  hidden_size = 150
  max_segment_len = 256

  warmup_ratio = 0.1
  max_grad_norm = 1  # Set 0 to disable clipping
  gradient_accumulation_steps = 1
  batch_size = 8

  # Model hyperparameters.
  activation = "relu"
  dropout_rate = 0.3
  num_epochs = 100

  # number of types
  num_typing_classes = 7
  num_linking_classes = 6
  lr_weight = 1.0

  rb_action_logit = false

  # Other.
  beam_size = 1

  eval_frequency = 3000
  report_frequency = 100
  conll_eval_path = none

  plm_tokenizer_name = t5-small
}

t5-small = ${training}{
  plm_learning_rate = 5e-5
  task_learning_rate = 3e-4
  warmup_ratio = 0.1

  hidden_size = 150
  eval_frequency = 1000

  plm_pretrained_name_or_path = t5-small
}


t5-base = ${training}{
  plm_learning_rate = 5e-5
  task_learning_rate = 3e-4
  warmup_ratio = 0.1

  hidden_size = 150
  eval_frequency = 1000

  plm_pretrained_name_or_path = t5-base
}

google_flan-t5-base = ${t5_base_ace05}{
  plm_pretrained_name_or_path = google/flan-t5-base
}

t5-large = ${training}{
  plm_learning_rate = 5e-5
  task_learning_rate = 3e-4
  warmup_ratio = 0.05

  hidden_size = 150
  eval_frequency = 1000

  plm_pretrained_name_or_path = t5-large
}
google_flan-t5-large = ${t5_large_ace05}{
  plm_pretrained_name_or_path = google/flan-t5-large
}

t5-3b = ${training}{
  plm_learning_rate = 5e-5
  task_learning_rate = 3e-4
  warmup_ratio = 0.05

  hidden_size = 150
  eval_frequency = 1000
  plm_pretrained_name_or_path = t5-3b
}


t0-3b = ${t5_3b_ace05}{
  plm_pretrained_name_or_path = bigscience/T0_3B
}

google_flan-t5-xl = ${t5_3b_ace05}{
  plm_pretrained_name_or_path = google/flan-t5-xl
}

t5-11b = ${t5_3b_ace05}{
  plm_pretrained_name_or_path = t5-11b
}

google_flan_t5_xxl = ${t5_3b_ace05}{
  plm_pretrained_name_or_path = bigscience/flan-t5-xxl
  eval_frequency = 2000
}
